title : David Ketcheson
tagline: Numerical analysis and nonlinear waves
author :
  name : David I. Ketcheson
  email : dketch@gmail.com

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

markdown: pandoc
pandoc:
   extensions: [smart, mathjax]

highlighter: pygments
source: .
lsi: True

pageviews: yes    ## toggle on sidebar pageviews 
gitstamps: yes
repo: https://github.com/ketch/labnotebook # used in linking history

baseurl: '/'

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
