title : Schur's Lemming
tagline:
author :
  name : Ninnat Dangniam
  givenName: Ninnat
  familyName: Dangniam
  ThaiName: นินนาท แดงเนียม
  twitter:
  github: ninnat
  email : truecrimson@gmail.com
  gplus:
  gscholar:
  facebook: ninnattom.dangniam
  linkedin:
  stackexchangephy:
  ghorgs: # Used in the Javascript of Community page to pull out github repos.
    - name: CQuIC
url: http://ninnat.github.io
disqus:
  sitename: ninnat # This is the shortname of the disqus site id to display disqus comments below posts.
addthis:  # Get an account at www.addthis.com. You may need to at least enable the Sharing Sidebar and Sharing Buttons functions to fully use our design.
  pubid: ra-5761ec473416b238 # This is the AddThis button pubid to display social sharing buttons on the website. Used in the header template.
navigation: # For the navigation menu. Don't use index.html. urls should end with a directory.
  - text: Main
    url: /
  - text: About
    url: /about/

permalink: /:title.html
redirects: yes
encoding: utf-8
pageviews: no    ## toggle on sidebar pageviews
twitter_api: no
analytics: UA-79420814-1 ## Google Analytics key UA-79420814-1 (in _includes/analytics.html and search.html)
baseurl: ''
lsi: True # Possibly for generating related posts with gsl and classifier packages.
future: true

# GitHub information of this site. Used for extracting commit history of posts.
gitstamps: yes
username: ninnat
orgname: ninnat # This is used to identify the category of GitHub repository. Use username for personal repository.
repo: ninnat.github.io # used in linking commit history and auto-deploy the site on travis-CI. The repository address will be identified as https://username:GH_TOKEN@github.com/orgname/repo.git defined in Rakefile.
sourcebranch: dev # used in linking commit history.

source: .
gems:
  - jekyll-pandoc
  - unicode # Maybe required by latex-decode 0.3.
#  - 'jekyll-twitter-plugin'
# Publications. Ref: http://tuxette.nathalievilla.org/?p=1426
# http://eric-tramel.github.io/working-automated-publications/
# csl style: https://github.com/citation-style-language/styles
gems:
  - "jekyll/scholar"
scholar:
  style: assets/APS.csl
  locale: en

  sort_by: year
  order: descending

  source: assets
  bibliography: Publications
  bibliography_template: bibtemplate

  replace_strings: true

  details_dir:    pubs
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"



## Markdown Parser
#markdown: kramdown
markdown: pandoc
markdown_ext: markdown,md
pandoc:
   extensions:
     - smart
     - mathjax

#highlighter: pygments

#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter: pygments

## Have pages & posts use their default layouts, respectively
# defaults:
#  -
#    scope:
#      path: ""
#      type: "pages"
#    values:
#      layout: "page"
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .travis.yml
  - _posts/*.Rmd
  - _posts/source
  - assets/_bootstrap-3.3.6
  - Dockerfile
  - build.R
  - _cache
  - Makefile
  - deploy.sh
  - fig.yml
  - _posts/source/
  - secret
